Add support for Lightning Labs LND node wallet
sulusolutions/gol402 pull request #11
Opened 2024-03-24 12:58 UTC by mubarak23

This PR has work on 
- initiate LND Wallet
- Pay for an invoice
- Unit test for pay for invoice

2024-03-25 05:32 UTC, SamuelAl requested changes
The code below uses the wrong LND API to pay an invoice, as it presupposes the preimage, which can only be known by the payer once an invoice has been paid. 

The correct API endpoint should be [SendPaymentV2](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2) according to the docs. Please see further comments below:

2024-03-25 05:43 UTC, SamuelAl commented
As far as I understand, the SettleInvoice API is meant to be used by the payee, ie. the node receiving the funds, not the payer. 

Apart from that, for LND node connection I recommend the use of the gRPC client instead of HTTP REST. It is not a requirement, but I suspect it will be make our life easier specially in what concerns the creation of a TLS connection. It also supports more efficient streaming that might be useful in the implementation of future features.

Two packages that might prove useful are:
- github.com/lightninglabs/lndclient
- github.com/lightningnetwork/lnd/lnrpc

With lndclient, paying an invoice would look something like this: 

```go
payReq := lndclient.SendPaymentRequest{
		Invoice:          invoice,
		MaxFee:           100,
		Timeout:          time.Duration(2e16),
		AllowSelfPayment: true,
	}
statusChan, errChan, err := client.Router.SendPayment(context.Background(), payReq)
if err != nil {
return nil, err
}

for {
  select {
  case paymentStatus, ok := <-statusChan:
	  // If the channel is closed, exit the loop.
	  if !ok {
		  return nil, fmt.Errorf("payment status channel closed")
	  }
  
	  if paymentStatus.State == lnrpc.Payment_SUCCEEDED {
		  preimage := fmt.Sprintf("%s", paymentStatus.Preimage.String())
		  return &PaymentResult{
			  Preimage: preimage,
		  }, nil
	  } else if paymentStatus.State == lnrpc.Payment_FAILED {
		  return nil, fmt.Errorf("payment failed: %v", paymentStatus.State)
	  }
	  // If the status is neither SUCCEEDED nor FAILED, continue waiting.
  
  case err := <-errChan:
	  return nil, err
  }
}
```

2024-03-25 05:46 UTC, SamuelAl commented
I would recommend to manually test your implementation with something like [Polar](https://lightningpolar.com/) to make sure the correct APIs are being used.

2024-03-25 07:40 UTC, mubarak23 commented
> The code uses the wrong LND API to pay an invoice, as it presupposes the preimage, which can only be known by the payer once an invoice has been paid.
> 
> The correct API endpoint should be [SendPaymentV2](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2) according to the docs. Please see further comments below:



> The code uses the wrong LND API to pay an invoice, as it presupposes the preimage, which can only be known by the payer once an invoice has been paid.
> 
> The correct API endpoint should be [SendPaymentV2](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2) according to the docs. Please see further comments below:

what is happening here is, we will generate an invoice, send it over to the payer, and then listen for the settlement of the invoice by the payer.

2024-03-25 07:43 UTC, mubarak23 commented
> As far as I understand, the SettleInvoice API is meant to be used by the payee, ie. the node receiving the funds, not the payer.
> 
> Apart from that, for LND node connection I recommend the use of the gRPC client instead of HTTP REST. It is not a requirement, but I suspect it will be make our life easier specially in what concerns the creation of a TLS connection. It also supports more efficient streaming that might be useful in the implementation of future features.
> 
> Two packages that might prove useful are:
> 
>     * github.com/lightninglabs/lndclient
> 
>     * github.com/lightningnetwork/lnd/lnrpc
> 
> 
> With lndclient, paying an invoice would look something like this:
> 
> ```go
> payReq := lndclient.SendPaymentRequest{
> 		Invoice:          invoice,
> 		MaxFee:           100,
> 		Timeout:          time.Duration(2e16),
> 		AllowSelfPayment: true,
> 	}
> statusChan, errChan, err := client.Router.SendPayment(context.Background(), payReq)
> if err != nil {
> return nil, err
> }
> 
> for {
>   select {
>   case paymentStatus, ok := <-statusChan:
> 	  // If the channel is closed, exit the loop.
> 	  if !ok {
> 		  return nil, fmt.Errorf("payment status channel closed")
> 	  }
>   
> 	  if paymentStatus.State == lnrpc.Payment_SUCCEEDED {
> 		  preimage := fmt.Sprintf("%s", paymentStatus.Preimage.String())
> 		  return &PaymentResult{
> 			  Preimage: preimage,
> 		  }, nil
> 	  } else if paymentStatus.State == lnrpc.Payment_FAILED {
> 		  return nil, fmt.Errorf("payment failed: %v", paymentStatus.State)
> 	  }
> 	  // If the status is neither SUCCEEDED nor FAILED, continue waiting.
>   
>   case err := <-errChan:
> 	  return nil, err
>   }
> }
> ```

I initially implemented the system with GRPC, but I didn't fully understand it. Therefore, I switched to a RESTful API. If we need to listen for invoice settlements, then GRPC will be suitable for us in this case.

2024-03-25 07:50 UTC, SamuelAl commented
I think there is some confusion here:  gol402 is a **client** library. gol402 does not generate any invoice. gol402, as an L402 client:

1. Attempts a request to an L402-monetized API,
2. Receives an L402 Request for Payment error containing a Lightning Invoice,
3. Pays for the Lightning invoice using a **wallet** implementation, which is the theme of this PR,
4. Retries the request with a newly assembled L402 token, which includes the preimage revealed by paying the fore-mentioned invoice.

gol402 does not run on Sulu servers, it runs on the client side, on the side of the computers trying to access L402 APIs. It runs on the side of the payer, not the payee. Its job is to catch incoming L402 errors and handle them by completing the L402 handshake, which requires the paying of an invoice.

Does this help clarify?

Happy to jump on a call on our discord server to further clarify this if needed.

2024-03-25 07:55 UTC, mubarak23 commented
Please let jump on call

2024-03-25 08:18 UTC, mubarak23 commented
> I think there is some confusion here: gol402 is a **client** library. gol402 does not generate any invoice. gol402, as an L402 client:
> 
>     1. Attempts a request to an L402-monetized API,
> 
>     2. Receives an L402 Request for Payment error containing a Lightning Invoice,
> 
>     3. Pays for the Lightning invoice using a **wallet** implementation, which is the theme of this PR,
> 
>     4. Retries the request with a newly assembled L402 token, which includes the preimage revealed by paying the fore-mentioned invoice.
> 
> 
> gol402 does not run on Sulu servers, it runs on the client side, on the side of the computers trying to access L402 APIs. It runs on the side of the payer, not the payee. Its job is to catch incoming L402 errors and handle them by completing the L402 handshake, which requires the paying of an invoice.
> 
> Does this help clarify?
> 
> Happy to jump on a call on our discord server to further clarify this if needed.

settle invoice will return the preimage, which the client will attempt to call the L402-monetized API

2024-03-26 06:20 UTC, SamuelAl requested changes
I am afraid I must reject this PR for multiple reasons:
- PR has multiple basic syntax errors. The code does not build (how were you able to run the unit tests?).
- Code has missing packages that have not been included in the go.mod, or even in the import declaration, therefore code does not build.
- Importantly, PR DOES NOT implement the Wallet interface as requested in the Issue description.
- LND client connection is missing several key parameters.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  	macaroonString []byte
It does not make sense to call a variable "String" if it is a []byte type.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  	BaseURL string
Since we are using gRPC we do not really need a BaseURL, which would be more common with REST APIs. With gRPC we usually deal with an address.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  type LNDWallet struct {
Connecting to a production LND node will require more parameters, including TLS certificate. Adding the network as a parameter also facilitates testing with regtest or testnet. Please review list of parameters.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  type LNDWallet struct {
LNDWallet should have a client attribute to maintain a node connection, rather than building the connection on each request.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  func NewLNDWallet(macaroonPath string,  address string) *LNDWallet {
This should initialize an LND gRPC client instance as part of the LNDWallet struct (see comments above). It is very innefficient to initialize a client for each request (very high latency).

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
> +func (lndw *NewLNDWallet) HandleSettleInvoice(ctx context.Context, invoice wallet.Invoice) (*wallet.PaymentLndResult, error) {
Please adhere to already existing Wallet interface as per Issue description and requirements. As it stands this wallet does not implement the Wallet interface.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
> +			return nil, "Payment status channel closed"
This will not build, you are returning a string as an error.

2024-03-26 06:20 UTC, SamuelAl commented on wallet/lnd/lnd.go
>  	"io/ioutil"
io/ioutil is deprecated since Go 1.16

2024-03-28 10:10 UTC, SamuelAl commented
I will close this PR for now.

2024-03-28 10:10 UTC, closed without merging